version: "3"

services:
  mosquitto:
    image: eclipse-mosquitto:2.0.18
    container_name: mosquitto
    environment:
      - TZ=Europe/Madrid  
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 8883:8883
    restart: unless-stopped